### PR TITLE
Change format for the command section in help text

### LINKED ISSUE #82: Replace the command section in help text with the current subcommand usage examples
Currently, the help text looks like this:

```bash
DiscordChatExporter.Cli v2.23.0

Usage
  dotnet DiscordChatExporter.Cli.dll [command] [options]

  ... exportall --token <value> [options]
  ... export --channel <value> --token <value> [options]
  ... exportdm --token <value> [options]
  ... exportguild --guild <value> --token <value> [options]
  ... channels --guild <value> --token <value> [options]
  ... dm --token <value> [options]
  ... guilds --token <value> [options]
  ... guide [options]

Options
  -h|--help         Shows help text.
  --version         Shows version information.

Commands
  exportall         Export all accessible channels.
  export            Export a channel.
  exportdm          Export all direct message channels.
  exportguild       Export all channels within specified guild.
  channels          Get the list of channels in a guild.
  dm                Get the list of direct message channels.
  guilds            Get the list of accessible guilds.
  guide             Explains how to obtain token, guild or channel ID.

You can run `dotnet DiscordChatExporter.Cli.dll [command] --help` to show help on a specific command.
```

This is a bit suboptimal, for few reasons:

1. Command names are duplicated
2. Command usage info and description are separated
3. The help text is too long

The suggestion is to change the help text to this instead:

```bash
DiscordChatExporter.Cli v2.23.0

Usage
  dotnet DiscordChatExporter.Cli.dll [command] [options]

Options
  -h|--help         Shows help text.
  --version         Shows version information.

Commands
  Export all acessible channels
    exportall --token <value>
  Export a channel
    export --channel <value> --token <value>
  Export all direct message channels
    exportdm --token <value>
  Export all channels within specified guild  
    exportguild --guild <value> --token <value>
  Get the list of channels in a guild
    channels --guild <value> --token <value>
  Get the list of direct message channels
     dm --token <value>
  Get the list of accessible guilds
     guilds --token <value>
  Explains how to obtain token, guild or channel ID
     guide

You can run `dotnet DiscordChatExporter.Cli.dll [command] --help` to show help on a specific command.
```

Vertical formatting instead of columns because command usage info can get rather large. Generally, the format is up to discussion, so ideas are welcome.

### PR DESCRIPTION
**Pull request by es-rene99**
BREAKING CHANGE: Removed test Help_text_shows_usage_format_which_lists_available_sub_commands, since usage will not longer show the subcommands

Closes #82

### CODE REVIEW

**Comment by Tyrrrz** [comment]
Can you please add a new test that verifies updated behavior, similar to others?
Also please post a screenshot of how it looks on CliFx.Demo

**Comment by es-rene99** [comment]
Hi @Tyrrrz, this is how the change looks in the CliFx.Demo project
image

Also I share with you a screenshot on how it would look a command has no description, I edited the Demo project for this demonstration
image
I would like to know your opinion, here a "No description available" could display, or the user should be encouraged to add a description to each command

And sure let me add a new test.

**Comment by Tyrrrz** [comment]
The first one looks good visually! For description-less commands, just remove that extra line break:

image

**Comment by es-rene99** [comment]
I updated the code, this is how it looks without the extra blank line: 
image

and how it looks with the description:
image

Please let me know if this is correct

**Comment by Tyrrrz** [comment]
Looks good! Can you also remove the extra vertical space before "You can run..." at the bottom?

**Comment by es-rene99** [comment]
No problem, I modified the code, this is how it currently looks:
image

**Comment by Tyrrrz** [comment]
Thanks!

**Pull request merged**
